### ISSUE TITLE
Don't close notification bar due to button handler return value

### ISSUE THREAD

**Issue by benbucksch** [jobisoft/notificationbar-API#7] opened 2020-10-23 14:41 UTC
WebExtension APIs don't have proper callbacks, only event handlers. That's why all button listeners for all notification bars on an extension get the same clicks, and then the handler needs to filter.

A trivial implementation of a button handler looks like this:
```javascript
browser.notificationBar.onButton.addListener((notificationBar, button) => {
  if (notificationBar == "a" && button == "open_button") {
    openDialog();
    return true;
  }
});
```

If any of my button event handlers does that and is not doing `return true;` after the `if` block as well, then my notification bar (on which button the user clicked) will close - even bar `b`.  So, if I have 2 notifications bars, and bar A should close on button click, and I'm omitting `return true;` in its button handler, and bar B should not close, and I do add `return true;` in its button handler, then the notification bar will nonetheless close, because the handler for bar A also executes and messes me up. This is going to lead to significant hair loss for many addon developers.

Personally, I would not close by default. I'd make an explicit `bar.close()`. This is not only safer, but also easier to read and understand when reading the extension code than a `return false;`, which could mean anything.

**Comment by jobisoft** [comment] 2020-10-26 09:28
I could not reproduce this to the full extent, as the listener callback is not called for all buttons, but just the clicked button. So a button in notificationbar A cannot close notificationbar B.

The question about default behaviour: I would like to stick to default close. But instead of returning true or false, we could return an object like the onBeforeSend Event:

https://thunderbird-webextensions.readthedocs.io/en/latest/compose.html#onbeforesend-tab-details

`{ close: false }`

**Comment by jobisoft** [comment] 2020-10-26 09:53
Implemented this in https://github.com/jobisoft/notificationBox-API/commit/0d79826f04fb62310987b272f1c07f11ec201c99.

Ok to close this issue?

**Comment by jobisoft** [comment] 2020-10-26 23:03
The mentioned change also takes care of the case, when multiple `onButtonClicked` listeners have been registered. As long as one of them returns `{ close:false }`, the notification bar stay open.

**Closed as completed** 2020-10-27 09:22 UTC

**Comment by NeilRashbrook** [comment] 2020-11-02 12:00
Thanks for fixing it so that a listener can't accidentally close another listener's notification.

**Comment by benbucksch** [comment] 2020-11-02 18:41
@jobisoft: What happens when the handler returns nothing = `undefined`, e.g. like the example in the initial description? (Or the handler returns an object which doesn't have a `close` property.) In this case, the handler should have no influence on the decision at all, neither force close nor force keep open, but leave it to the other handlers to decide. That avoids code accidents. This will be a very common case, as the example shows when the `if` does not match and execution drops to the end of the function.

If there are no other handlers, or none of the handlers specifically state to close the bar, I think it should stay open. That allows the handler to alternatively use an API that explicitly calls `bar.close()` in the handler code, as needed, instead of using the return value. It also makes the API generally more predictable and less prone to accidential behavior.
